/**
 * Custom Ghost Application Entry Point
 *
 * This file is copied into the Ghost install directory by the Dockerfile
 * and replaces the default index.js generated by ghost-cli.
 *
 * You have full control here to add any middleware before or after Ghost.
 */

const express = require('express');
const ghost = require('ghost');
const path = require('path');

async function start() {
  const app = express();

  // Boot Ghost (it will pick up config from the current directory)
  const ghostServer = await ghost();

  // Mount Ghost's entire application
  app.use(ghostServer.rootApp);

  // ============================================================
  // ADD YOUR CUSTOM MIDDLEWARE AND ROUTES HERE
  // ============================================================

  // 1. Request logging middleware
  app.use((req, res, next) => {
    const start = Date.now();
    res.on('finish', () => {
      console.log(`[Custom] ${req.method} ${req.originalUrl} ${res.statusCode} ${Date.now() - start}ms`);
    });
    next();
  });

  // 2. Custom health endpoint (great for Docker healthchecks)
  app.get('/health', (req, res) => {
    res.json({
      status: 'ok',
      service: 'paid-blog-custom-ghost',
      database: 'sqlite',
      middleware: 'active',
      timestamp: new Date().toISOString()
    });
  });

  // 3. Example: Future payment/subscription middleware
  // app.use('/members/api', verifyActiveSubscription);
  // app.use('/api/paid', requirePaidAccess);

  // ============================================================
  // END CUSTOM MIDDLEWARE
  // ============================================================

  // Start the server (Ghost config controls the port via environment or config file)
  const port = process.env.PORT || 3000;
  app.listen(port, '0.0.0.0', () => {
    console.log(`Custom Ghost app listening on port ${port}`);
  });
}

start().catch((err) => {
  console.error('Failed to boot custom Ghost:', err);
  process.exit(1);
});
